################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TODISASSEMBLE_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
O_SRCS_QUOTED := 
LD_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
O_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
TOPREPROCESS_SRCS_OS_FORMAT := 
OSPT_SRCS := 
O_SRCS := 
ELF_SRCS := 
TOPREPROCESS_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_SRCS_QUOTED := 
S_SRCS_QUOTED := 
ELF_SRCS_QUOTED := 
ELF_SRCS_OS_FORMAT := 
ASM_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
ASM_SRCS := 
S_UPPER_SRCS_OS_FORMAT := 
S_UPPER_SRCS := 
ASM_SRCS_QUOTED := 
OBJ_SRCS_QUOTED := 
LD_SRCS := 
OSPT_SRCS_QUOTED := 
LD_SRCS_QUOTED := 
OBJ_SRCS := 
S_SRCS := 
TOPREPROCESS_SRCS := 
C_SRCS := 
ASM_UPPER_SRCS_OS_FORMAT := 
OSPT_SRCS_OS_FORMAT := 
SECONDARY_FLASH_QUOTED := 
SECONDARY_SIZE_OS_FORMAT := 
C_DEPS_QUOTED := 
SECONDARY_SIZE := 
OBJS_QUOTED := 
C_DEPS := 
C_DEPS_OS_FORMAT := 
OBJS_OS_FORMAT := 
EXECUTABLES_OS_FORMAT := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_FLASH_OS_FORMAT := 
SECONDARY_SIZE_QUOTED := 
EXECUTABLES_QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Generated_Code \
Project_Settings/Startup_Code \
SDK/middleware/tcpip/lwip/src/api \
SDK/middleware/tcpip/lwip/src/apps/lwiperf \
SDK/middleware/tcpip/lwip/src/apps/mdns \
SDK/middleware/tcpip/lwip/src/apps/mqtt \
SDK/middleware/tcpip/lwip/src/apps/snmp \
SDK/middleware/tcpip/lwip/src/apps/tftp \
SDK/middleware/tcpip/lwip/src/core \
SDK/middleware/tcpip/lwip/src/core/ipv4 \
SDK/middleware/tcpip/lwip/src/core/ipv6 \
SDK/middleware/tcpip/lwip/src/netif \
SDK/middleware/tcpip/lwip/src/netif/ppp \
SDK/middleware/tcpip/lwip/src/netif/ppp/polarssl \
SDK/middleware/tcpip/tcpip_stack/addons/tcp_isn \
SDK/middleware/tcpip/tcpip_stack/apps/chargen \
SDK/middleware/tcpip/tcpip_stack/apps/httpserver \
SDK/middleware/tcpip/tcpip_stack/apps/smtp \
SDK/middleware/tcpip/tcpip_stack/apps/snmp_private_mib \
SDK/middleware/tcpip/tcpip_stack/apps/tcpecho \
SDK/middleware/tcpip/tcpip_stack/apps/udpecho \
SDK/middleware/tcpip/tcpip_stack/demo \
SDK/middleware/tcpip/tcpip_stack/ports/OS \
SDK/middleware/tcpip/tcpip_stack/ports/netif/enetif \
SDK/platform/devices/MPC5748G/startup \
SDK/platform/devices \
SDK/platform/drivers/src/clock/MPC57xx \
SDK/platform/drivers/src/clock \
SDK/platform/drivers/src/dspi \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/enet \
SDK/platform/drivers/src/flexcan \
SDK/platform/drivers/src/interrupt \
SDK/platform/drivers/src/linflexd \
SDK/platform/drivers/src/pins \
SDK/platform/drivers/src/usdhc \
SDK/rtos/FreeRTOS_C55/Source \
SDK/rtos/FreeRTOS_C55/Source/portable/GCC/PowerPC_Z4 \
SDK/rtos/FreeRTOS_C55/Source/portable/MemMang \
SDK/rtos/osif \
Sources \
lwip/src/api \
lwip/src/apps/lwiperf \
lwip/src/apps/mdns \
lwip/src/apps/mqtt \
lwip/src/apps/netbiosns \
lwip/src/apps/snmp \
lwip/src/apps/sntp \
lwip/src/apps/tftp \
lwip/src/core \
lwip/src/core/ipv4 \
lwip/src/core/ipv6 \
lwip/src/netif \
lwip/src/netif/ppp \
lwip/src/netif/ppp/polarssl \

